version: '3'
services:
  db:
    image: mysql:5.7
    tmpfs: /var/lib/mysql:rw
    command: [
        'mysqld',
        '--innodb-buffer-pool-size=20M',
        '--character-set-server=utf8',
        '--collation-server=utf8_general_ci',
        '--default-time-zone=+8:00',
        '--lower-case-table-names=1'
      ]
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_DATABASE=parking"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_ROOT_PASSWORD=12345"
    ports:
      - "3306:3306"
