spring:
    datasource:
        url: jdbc:mysql://localhost:3306/parking?characterEncoding=UTF-8
        username: root
        password: 12345
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        open-in-view: false